---
title: "Project 2"
author: "Sneha Khandelwal"
date: "2023-03-20"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load the mlbench package which has the BreastCancer data set
require(mlbench)
```

```{r}
# if you don't have any required package, use the install.packages() command
# load the data set
data(BreastCancer)
ls(BreastCancer)
str(BreastCancer)
# some algorithms don't like missing values, so remove rows with missing values
BreastCancer <- na.omit(BreastCancer) 
# remove the unique identifier, which is useless and would confuse the machine learning algorithms
BreastCancer$Id <- NULL 
head(BreastCancer)
str(BreastCancer)
df2 <- data.frame(sapply(BreastCancer[1:9], function(x) as.numeric(as.character(x))))
z<-scale(df2[,1:9],center=TRUE,scale=TRUE)
head(z)
library(e1071)

```

```{r}
#support vector machine
mysvm <-svm(Class ~ ., BreastCancer)
mysvm.pred <-predict(mysvm, BreastCancer)
table(mysvm.pred,BreastCancer$Class)
```

```{r}
#install.packages("klar")
library(klaR)

mynb<-NaiveBayes(Class~., BreastCancer)
mynb.pred<-predict(mynb, BreastCancer)
head(mynb.pred$class)
table(mynb.pred$class,BreastCancer$Class)

```

```{r}
str(mysvm.pred)
str(mynb.pred)
```

```{r}


#Decision trees
library(rpart)
mytree <- rpart(Class~.,BreastCancer)
plot(mytree); text(mytree)
summary(mytree)
mytree.pred <- predict(mytree,BreastCancer,type="class")
table(mytree.pred,BreastCancer$Class)
str(mytree)
```

```{r}
#rpart.plot package
library(rpart.plot)
rpart.rules(mytree)
rpart.plot(mytree)
```

```{r}
#Leave-1-out Cross Validation(LOOCV)
ans <-numeric(length(BreastCancer[,1]))
for(i in 1:length(BreastCancer[,1])) {
  mytree <- rpart(Class ~., BreastCancer[-i,])
  mytree.pred <- predict(mytree,BreastCancer[i,],type="class")
  ans[i] <- mytree.pred
}
ans <- factor(ans,labels=levels(BreastCancer$Class))
table(ans,BreastCancer$Class)
```


```{r}
#Regularized Discriminant Analysis
library(klaR)
myrda <- rda(Class ~., BreastCancer)
myrda.pred <- predict(myrda,BreastCancer)
table(myrda.pred$class,BreastCancer$Class)
```

```{r}
#Random Forests
library(randomForest)
myrf <- randomForest(Class ~., BreastCancer)
myrf.pred <- predict(myrf, BreastCancer)
head(myrf.pred)
table(myrf.pred, BreastCancer$Class)
```

```{r}
combine.classes <- data.frame(mysvm.pred,myrf.pred,myrda.pred,mytree.pred)
head(combine.classes)  
head(myrf.pred)
head(myrda.pred)
combine.classes$myrf.pred <- ifelse(combine.classes$myrf.pred=="benign",0,1)
combine.classes[,2] <- ifelse(combine.classes[,2]=="benign",0,1)
combine.classes[,3] <- ifelse(combine.classes[,3]=="benign",0,1)
str(combine.classes)
```


#combine.cl <- combine.classes[,-c(4,5)]
#majority.vote=rowSums(combine.classes[,-c(4,5)])
#head(majority.vote)
#data.frame(mysvm.pred,myrf.pred,myrda.pred$Class,#myqda.pred,
#                              mytree.pred,mynb.pred$class)

```{r}                           
head(combine.classes)
head(myrf.pred)
head(myrda.pred)
combine.classes$myrf.pred <- ifelse(combine.classes$myrf.pred=="benign",0,1)
combine.classes[,2] <- ifelse(combine.classes[,2]=="benign",0,1)
combine.classes[,3] <- ifelse(combine.classes[,3]=="benign",0,1)
combine.classes[,4] <- ifelse(combine.classes[,4]=="benign",0,1)
combine.classes[,5] <- ifelse(combine.classes[,5]=="benign",0,1)
#combine.classes[,6] <- ifelse(combine.classes[,6]=="benign",0,1)
str(combine.classes)
#combine.cl <- combine.classes[,-c(6,7)]
#majority.vote=rowSums(combine.classes[,-c(6,7)])
#head(majority.vote)
#head(combine.cl)
#combine.classes[,6]<- rowSums(combine.classes[,-c(6,7)])
#combine.classes[,7]<-ifelse(combine.classes[,6]>=4, "malignant", benign)
head(combine.classes)
#table(combine.classes[,7], BreastCancer$Class)
```

```{r}
# partition the data set for 80% training and 20% evaluation (adapted from ?randomForest)
set.seed(2)

ind <- sample(2, nrow(BreastCancer), replace = TRUE, prob=c(0.8, 0.2))

# create model using recursive partitioning on the training data set
require(rpart)
x.rp <- rpart(Class ~ ., data=BreastCancer[ind == 1,])
# predict classes for the evaluation data set
x.rp.pred <- predict(x.rp, type="class", newdata=BreastCancer[ind == 2,])
# score the evaluation data set (extract the probabilities)
x.rp.prob <- predict(x.rp, type="prob", newdata=BreastCancer[ind == 2,])

# To view the decision tree, uncomment this line.
# plot(x.rp, main="Decision tree created using rpart")

# create model using conditional inference trees
require(party)
x.ct <- ctree(Class ~ ., data=BreastCancer[ind == 1,])
x.ct.pred <- predict(x.ct, newdata=BreastCancer[ind == 2,])
x.ct.prob <-  1- unlist(treeresponse(x.ct, BreastCancer[ind == 2,]), use.names=F)[seq(1,nrow(BreastCancer[ind == 2,])*2,2)]

# To view the decision tree, uncomment this line.
# plot(x.ct, main="Decision tree created using condition inference trees")

# create model using random forest and bagging ensemble using conditional inference trees
x.cf <- cforest(Class ~ ., data=BreastCancer[ind == 1,], control = cforest_unbiased(mtry = ncol(BreastCancer)-2))
x.cf.pred <- predict(x.cf, newdata=BreastCancer[ind == 2,])
x.cf.prob <-  1- unlist(treeresponse(x.cf, BreastCancer[ind == 2,]), use.names=F)[seq(1,nrow(BreastCancer[ind == 2,])*2,2)]

# create model using bagging (bootstrap aggregating)
require(ipred)
x.ip <- bagging(Class ~ ., data=BreastCancer[ind == 1,])
x.ip.prob <- predict(x.ip, type="prob", newdata=BreastCancer[ind == 2,])

# create model using svm (support vector machine)
require(e1071)

# svm requires tuning
x.svm.tune <- tune(svm, Class~., data = BreastCancer[ind == 1,],
                   ranges = list(gamma = 2^(-8:1), cost = 2^(0:4)),
                   tunecontrol = tune.control(sampling = "fix"))
# display the tuning results (in text format)
x.svm.tune
# If the tuning results are on the margin of the parameters (e.g., gamma = 2^-8), 
# then widen the parameters.
# I manually copied the cost and gamma from console messages above to parameters below.
x.svm <- svm(Class~., data = BreastCancer[ind == 1,], cost=4, gamma=0.0625, probability = TRUE)
x.svm.prob <- predict(x.svm, type="prob", newdata=BreastCancer[ind == 2,], probability = TRUE)


##
## plot ROC curves to compare the performance of the individual classifiers
##

# Output the plot to a PNG file for display on web.  To draw to the screen, 
# comment this line out.
png(filename="roc_curve_5_models.png", width=700, height=700)

# load the ROCR package which draws the ROC curves
require(ROCR)

# create an ROCR prediction object from rpart() probabilities
x.rp.prob.rocr <- prediction(x.rp.prob[,2], BreastCancer[ind == 2,'Class'])
# prepare an ROCR performance object for ROC curve (tpr=true positive rate, fpr=false positive rate)
x.rp.perf <- performance(x.rp.prob.rocr, "tpr","fpr")
# plot it
plot(x.rp.perf, col=2, main="ROC curves comparing classification performance of five machine learning models")

# Draw a legend.
legend(0.6, 0.6, c('rpart', 'ctree', 'cforest','bagging','svm'), 2:6)

# ctree
x.ct.prob.rocr <- prediction(x.ct.prob, BreastCancer[ind == 2,'Class'])
x.ct.perf <- performance(x.ct.prob.rocr, "tpr","fpr")
# add=TRUE draws on the existing chart 
plot(x.ct.perf, col=3, add=TRUE)


# cforest
x.cf.prob.rocr <- prediction(x.cf.prob, BreastCancer[ind == 2,'Class'])
x.cf.perf <- performance(x.cf.prob.rocr, "tpr","fpr")
plot(x.cf.perf, col=4, add=TRUE)

# bagging
x.ip.prob.rocr <- prediction(x.ip.prob[,2], BreastCancer[ind == 2,'Class'])
x.ip.perf <- performance(x.ip.prob.rocr, "tpr","fpr")
plot.new()
plot(x.ip.perf, col=5, add=TRUE)
# svm
x.svm.prob.rocr <- prediction(attr(x.svm.prob, "probabilities")[,2], BreastCancer[ind == 2,'Class'])
x.svm.perf <- performance(x.svm.prob.rocr, "tpr","fpr")

plot(x.svm.perf, col=6, add=TRUE)

# Close and save the PNG file.
dev.off()
```
